name: OffGallery
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=h981015d_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - argostranslate==1.10.0
      - blis==1.3.3
      - catalogue==2.0.10
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpathlib==0.23.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - confection==0.1.5
      - contourpy==1.3.3
      - ctranslate2==4.6.1
      - cycler==0.12.1
      - cymem==2.0.13
      - cython==3.2.1
      - easydict==1.13
      - einops==0.8.1
      - emoji==2.15.0
      - en-core-web-sm==3.8.0
      - exifread==3.5.1
      - filelock==3.19.1
      - flatbuffers==25.9.23
      - fonttools==4.61.0
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==3.11
      - imageio==2.37.2
      - insightface==0.7.3
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - murmurhash==1.0.15
      - networkx==3.6
      - numpy==2.2.6
      - onnx==1.19.1
      - onnxruntime-gpu==1.23.2
      - open-clip-torch==3.2.0
      - opencv-contrib-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - preshed==3.0.12
      - prettytable==3.17.0
      - protobuf==6.33.1
      - pybioclip==2.1.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - pyqt6==6.10.0
      - pyqt6-qt6==6.10.1
      - pyqt6-sip==13.10.2
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - ram==0.0.1
      - rawpy==0.25.1
      - regex==2025.11.3
      - requests==2.32.5
      - sacremoses==0.1.1
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - sentence-transformers==5.1.2
      - sentencepiece==0.2.1
      - simsimd==6.5.3
      - six==1.17.0
      - smart-open==7.5.0
      - spacy==3.8.11
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.2
      - stanza==1.10.1
      - stringzilla==4.4.0
      - sympy==1.14.0
      - thinc==8.3.10
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - timm==1.0.22
      - tokenizers==0.22.1
      - torch==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - tqdm==4.67.1
      - transformers==4.57.3
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wasabi==1.1.3
      - wcwidth==0.2.14
      - weasel==0.4.3
      - wrapt==2.0.1
      - xx-sent-ud-sm==3.8.0
prefix: OffGallery
